# Generated by Django 5.1.1 on 2025-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_managerinfo_employeeinfo_delete_organizationemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
