# Generated by Django 5.1.1 on 2025-06-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_managerinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
